# Generated by Django 5.2.4 on 2025-07-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
