# Generated by Django 5.2.4 on 2025-07-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_alter_booking_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('Credit Card', 'credit card'), ('Debit Card', 'debit card'), ('Cash', 'cash'), ('Online', 'on;ine')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Failed', 'failed'), ('Completed', 'completed')], default='pending', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
